# Generated by Django 2.2.5 on 2019-09-19 18:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='наименование')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('active', models.BooleanField(default=True, verbose_name='активно')),
                ('start_date', models.DateTimeField(verbose_name='дата начала')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='дата окончания')),
                ('start_time', models.TimeField(blank=True, verbose_name='время начала')),
                ('everyday', models.BooleanField(verbose_name='каждый день')),
                ('day_of_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='день месяца')),
                ('monday', models.BooleanField(verbose_name='понедельник')),
                ('tuesday', models.BooleanField(verbose_name='вторник')),
                ('wednesday', models.BooleanField(verbose_name='среда')),
                ('thursday', models.BooleanField(verbose_name='четверг')),
                ('friday', models.BooleanField(verbose_name='пятница')),
                ('saturday', models.BooleanField(verbose_name='суббота')),
                ('sunday', models.BooleanField(verbose_name='воскресенье')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
    ]
